import fse from "fs-extra";
import path from "path";
// @ts-ignore: doesn’t deal with json files
import { version } from "../package.json";
import { LanguageCodegen, MainCodegen, TsCodegen } from "./Codegen";
import mergeFormats from "./formats";
import { GeneratedCode, Options } from "./intl-codegen";
import Language from "./Language";

const BANNER =
  `
// DO NOT MODIFY
// FILE GENERATED BY \`intl-codegen@${version}\`
// https://github.com/eversport/intl-codegen
// DO NOT MODIFY
  `.trim() + "\n\n";

class IntlCodegen {
  private languages = new Map<string, Language>();
  private options: Required<Options>;

  // TODO: remove fallback to string with v2
  constructor(options: Options | string = {}) {
    if (typeof options === "string") {
      options = { defaultLocale: options };
    }
    this.options = {
      defaultLocale: options.defaultLocale || "en",
      formats: mergeFormats(options.formats),
    };

    this.getLanguage(this.options.defaultLocale);
  }

  public getLanguage(locale: string) {
    const { languages } = this;
    let language = languages.get(locale);
    if (!language) {
      language = new Language(locale);
      languages.set(locale, language);
    }
    return language;
  }

  public generateFiles(): GeneratedCode {
    const { languages, options } = this;
    const files: { [key: string]: string } = {};

    for (const [locale, language] of languages) {
      const fileName = `${locale}.js`;
      const codegen = new LanguageCodegen(language, options);
      files[fileName] = BANNER + codegen.generate();
    }

    const mainCodegen = new MainCodegen(languages, options);
    files["index.js"] = BANNER + mainCodegen.generate();

    const tsCodegen = new TsCodegen(languages, options);
    files["index.d.ts"] = BANNER + tsCodegen.generate();

    return files;
  }

  public async writeFiles(outputDirectory: string) {
    const files = this.generateFiles();
    for (const [_fileName, contents] of Object.entries(files)) {
      const fileName = path.join(outputDirectory, _fileName);
      await fse.ensureFile(fileName);
      await fse.outputFile(fileName, contents);
    }
    return files;
  }
}

export default IntlCodegen;
